version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 6543:5432

  openvidu:
    image: openvidu/openvidu-server-kms:latest
    environment:
      OPENVIDU_SECRET: ${OPENVIDU_SECRET}
    ports:
      - 4443:4443

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080