version: '3.8'

services:
  db:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    ports:
      - "6543:5432"
    networks:
      - backend-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8181:8080"
    depends_on:
      - db
    networks:
      - backend-network

  openvidu:
    image: openvidu/openvidu-server-kms:latest
    restart: always
    environment:
      OPENVIDU_SECRET: ${OPENVIDU_SECRET}
      TZ: America/Sao_Paulo
    ports:
      - "4443:4443"
    networks:
      - backend-network

  entretien-backend-app:
    image: netomantonio/entretien-backend-app
    restart: always
    build: ./app
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/${POSTGRES_DB}?timezone=America/Sao_Paulo
      SPRING.DATASOURCE.PASSWORD: ${POSTGRES_PASSWORD}
      SPRING.DATASOURCE.USERNAME: ${POSTGRES_USER}
    ports:
      - "5000:5000"
    expose:
      - 5000
    command: bash -c "./gradlew bootRun -Dorg.gradle.daemon=false"
    depends_on:
      - db
      - openvidu
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge