version: '3.8'

services:
  db:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_USER: user
    ports:
      - 6543:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    depends_on:
      - db

  openvidu:
    image: openvidu/openvidu-server-kms:latest
    environment:
      OPENVIDU_SECRET: ${OPENVIDU_SECRET}
    ports:
      - 4443:4443
