x-github:
  secrets:
    POSTGRES_URL:
    POSTGRES_PORT:
    POSTGRES_PASSWORD:
    POSTGRES_DB:
    POSTGRES_USER:
    OPENVIDU_SECRET:
    APPLICATION_SERVER_PORT:

version: '3.8'

services:
  entretien-backend-app:
    image: netomantonio/entretien-backend-app
    restart: always
    build: ./app
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://$${secrets.POSTGRES_URL}:$${POSTGRES_PORT}/$${POSTGRES_DB}?timezone=America/Sao_Paulo
      SPRING.DATASOURCE.PASSWORD: $${POSTGRES_PASSWORD}
      SPRING.DATASOURCE.USERNAME: $${POSTGRES_USER}
      SERVER.PORT: $${secrets.APPLICATION_SERVER_PORT}
    ports:
      - "$${secrets.APPLICATION_SERVER_PORT}:$${secrets.APPLICATION_SERVER_PORT}"
    expose:
      - $${secrets.APPLICATION_SERVER_PORT}
    command: bash -c "./gradlew bootRun -Dorg.gradle.daemon=false"



