keycloak:
  realm: entretien-rh
  resource: entretien-rh
  bearer-only: true
  auth-server-url: http://localhost:8282
  credentials:
      secret: 3jT2z52Wtp7p2VnsRLTtv6M4HQDtXPOx
      user-name: example_user
      password: password
