entretien:
  app:
    jwtSecret: secret
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}
server:
  port: ${APPLICATION_SERVER_PORT:5000}
spring:
  mvc:
    interceptor:
      enabled: true
      exclude: /health
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost}:${POSTGRES_PORT:6543}/${POSTGRES_DB:db}?timezone=America/Sao_Paulo
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
OPENVIDU:
  url: ${OPENVID_UR:localhost:4443}
  secret: ${OPENVIDU_SECRET:entretien-rh}