entretien:
  app:
    jwtSecret: secret
    jwtExpirationMs: ${JWT_EXPIRATION_MS}
server:
  port: ${APPLICATION_SERVER_PORT}
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}?timezone=America/Sao_Paulo
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true

OPENVIDU:
  url: ${OPENVID_URL}
  secret: ${OPENVIDU_SECRET}