entretien:
  app:
    jwtSecret: secret
    jwtExpirationMs: 86400000
server:
    port: 5000
spring:
  datasource:
    url: jdbc:postgresql://db-entretien.c7vy4anjujjj.us-east-1.rds.amazonaws.com:5432/db_entretien?timezone=America/Sao_Paulo
    driverClassName: org.postgresql.Driver
    username: entretien_be
    password: password
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true

OPENVIDU:
  url: http://localhost:4443/
  secret: entretien-rh